package com.rococo.springboot.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.rococo.springboot.model.DiseaseModel;
import com.rococo.springboot.repository.DiseaseRepository;

@Service
public class DiseaseServiceImpl {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private DiseaseRepository medRecordRepository;

	public DiseaseModel getDiseaseById(int given) {
		return medRecordRepository.findById(given).get();
	}
        
        public DiseaseModel getDiseaseByName(String given) {
		return medRecordRepository.findDiseaseByName(given);
	}
        
        public void removeMedicine(DiseaseModel disease){
            medRecordRepository.deleteById(disease.getId());
        }
        

	public List<DiseaseModel> getAll() {
		List<DiseaseModel> list = new ArrayList<>();
		medRecordRepository.findAll().iterator().forEachRemaining(list::add);
		return list;
	}

	/* (non-Javadoc)
	 * @see com.rococo.springboot.service.PersonService#registerPerson(com.rococo.springboot.model.DiseaseModel)
	 */
	public void registerMedicine(DiseaseModel medRecordModel) {
		medRecordRepository.save(medRecordModel);
                
	}

}
