package com.rococo.springboot.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.rococo.springboot.model.MedicalRecordModel;
import com.rococo.springboot.repository.MedicalRecordRepository;

@Service
public class MedicalRecordServiceImpl {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private MedicalRecordRepository medRecordRepository;

	public MedicalRecordModel getMedicalRecordInfo(MedicalRecordModel medRecordModel) {
		return medRecordRepository.findById(medRecordModel.getId()).get();
	}
        
        public void removeMedicine(MedicalRecordModel medicine){
            medRecordRepository.deleteById(medicine.getId());
        }
        

	public List<MedicalRecordModel> getAll() {
		List<MedicalRecordModel> list = new ArrayList<>();
		medRecordRepository.findAll().iterator().forEachRemaining(list::add);
		return list;
	}

	/* (non-Javadoc)
	 * @see com.rococo.springboot.service.PersonService#registerPerson(com.rococo.springboot.model.MedicalRecordModel)
	 */
	public void registerMedicine(MedicalRecordModel medRecordModel) {
		medRecordRepository.save(medRecordModel);
	}

}
